### ISSUE TITLE
Modeller scripts and alignments appear to be missing

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/NPC_3.0#1]
@iecheverria a number of PDB files look like Modeller outputs, e.g. `integrative_structure_modeling/pom152_isolated/data/pom152_E.pdb`. However the Modeller scripts and alignments used to build these models don't appear to be present. Can you add these?

**Comment by iecheverria** [comment]
Added in [42fd57f](https://github.com/integrativemodeling/NPC_3.0/commit/42fd57f641fe1f29bb17e6a376ab1f205aa90b82)
